### ISSUE TITLE
Wrinkles look a bit too fugly from the front

### ISSUE THREAD

**Issue by Lady-Luck** [Killface1980/RW_FacialStuff#15]
This is something that's been bothering me for a while, when looking straight at a pawn the wrinkles kind of make it look they have some sort of mandibles on their face around the mouth area. Really BUGs me! :p

**Comment by Lady-Luck** [comment]
Ah, I see the issue... it's when the mouth is hidden (which it seems to always be by default) that wrinkles look exceptionally ugly.

I'm honestly surprised there's no setting I can flip to make mouths be enabled by default.

**Comment by Killface1980** [comment]
I'm changing the wrinkle strength calculation. The mouths were disabled after many people complained about them, and they are of rather low quality compared to the rest. They are only accessible from the FS bench, don't know a better place for the options. I'm thinking of adding a global button to the bench.

**Comment by Lady-Luck** [comment]
I would say adding an option to HugsLib Mod Settings to have it default to on would be nice, but I think you got rid of the HugsLib dependency for some reason?

**Comment by Killface1980** [comment]
Yes, the less my mods depend on others, the easier maintenance should be. 
I rewrote parts of the code now, so that I don't need a MapComponent any more. I'm hesitating on adding the dependency again, I'm more focused on getting ToolsForHaul to work and fixing the Bar.
I've re-enable the mouths by default again, would need a place to save this value.

**Comment by Lady-Luck** [comment]
Well, there's always ini files.

**Comment by Lady-Luck** [comment]
Mouths don't appear to be on by default in the latest github version.

**Comment by Killface1980** [comment]
Yes, I decided to keep the mouths still disabled till I have found a solution. I'd need to rewrite some parts of the FS bench, as I want to explore how much custom skin colors RimWorld can handle. Also I'm thinking about presets, to make all your colonists look like the Children of the Corn etc. Still the Colonist Bar has some flaws, as the group rects when caravans are formed. Consider the state of my mods as RimWorld state – still alpha, much to do, and everything can change anytime ;c) 

By the way, what do you think of new suits (possible new mod, highly overpowered)? 
![image](https://cloud.githubusercontent.com/assets/16738568/21775292/c9087c76-d695-11e6-9371-b6e3807c433a.png)

**Comment by Lady-Luck** [comment]
Oh man they look awesome!

Would I be able to beg you to get a new Facial Stuff release out sooner rather than later with that wrinkle change you mentioned? I particularly want to see the four dots that surround the mouth gone when the mouth is off - or just removed entirely if that's too much trouble. It really does make old pawns look downright alien unless you have their mouths on.

Even decreasing wrinkle severity is gonna leave those four dots.

**Comment by Killface1980** [comment]
Weird, I already changed the calculation, might still be a little rough. I've just uploa a version with the mouths enabled by default + 60 % of the wrinkle strength. 

I'll attach the suits  here if you want to play around with them, but they are not balanced, and the Supe Suit makes the wearer basically invincible =) Best to be spawned and used for cheating. I'll need some more textures, define the stats, and of course add some more costumes for a full release.
[Less Serious.zip](https://github.com/Killface1980/RW_FacialStuff/files/694468/Less.Serious.zip)
