### ISSUE TITLE
Pawn Generation is expensive

### ISSUE THREAD

**Issue by Lady-Luck** [Killface1980/RW_FacialStuff#16]
Minor issue, but using this mod with Verify Start reveals that it makes pawn generation a lot more expensive by default, generating lots of pawns is about 1/3 speed.

Not sure if this can be fixed.

**Comment by Killface1980** [comment]
Unfortunately not fixable, as each time a pawn is created, also his appearance is defined and the textures are merged. This takes up additional RAM and some time to accomplish. I'm not very experienced in texture handling, and Unity is not very friendly towards textures loaded in-game.

**Comment by Lady-Luck** [comment]
Debug messages appear to have been left on in the current build on the workshop, which is making pawn generation more expensive.

**Comment by Killface1980** [comment]
removed the log, current Git version is clean. Will update the Steam version soonish.
