### ISSUE TITLE
Weird hair color bleed

### ISSUE THREAD

**Issue by Lady-Luck** [Killface1980/RW_FacialStuff#19]
http://i.imgur.com/8RLoTeS.png

Don't know why but certain hair colors (like this one) completely bleed outside the outline.

**Comment by Killface1980** [comment]
this can happen on some hair styles, where the hair has greyish or white semi-transparent pixels. With the "weird" hair colors, this becomes rather obvious, while natural colors like brown, black, blonde cover this issue. A fix would be either cleaning up the textures in Photoshop and adding the modified hair to the mod, or coming up with some kind of threshold for transparency in the pixel merging process.

**Comment by Lady-Luck** [comment]
Is this still an outstanding issue in the latest build?

**Comment by Killface1980** [comment]
I think so, it's just updated for A17. Will look into the textures provided by this mod and clean up any pixels outside of the outline.
Thanks for the reminder!

**Comment by Killface1980** [comment]
Should be fixed, I changed the alpha.
