### ISSUE TITLE
Facial Stuff settings do not save

### ISSUE THREAD

**Issue by Lady-Luck** [Killface1980/RW_FacialStuff#20]
The setting in question being the only setting, Add mouths to colonists.

No xml seems to be getting generated in the Config directory where the Colonist Bar settings are stored.

**Comment by Killface1980** [comment]
FS doesn't need an xml, the data is stored in the save game.
Only the bar uses xml files for saving.

**Comment by Lady-Luck** [comment]
>FS doesn't need an xml, the data is stored in the save game.
Only the bar uses xml files for saving.

Ah, I always tried to change the setting prior to starting a game through the options > mod settings menu on the main screen...
