### ISSUE TITLE
Just bringing this to your attention

### ISSUE THREAD

**Issue by Lady-Luck** [Killface1980/RW_FacialStuff#21]
Someone else has figured out how to make hats not hide hair, I'm not sure if it's an improvement on your method or not.

http://steamcommunity.com/sharedfiles/filedetails/?id=931727676

**Comment by Killface1980** [comment]
yes, but every hat def will need "<thingClass>Vanya_Headgear.HeadgearFrame</thingClass>" added. that means e.g. two Apparello versions.
also the original hair is visible above the hat. my method masks it. thanks for the link :)
