### ISSUE TITLE
Massive differences in quality between Workshop and Github PawnRenderer

### ISSUE THREAD

**Issue by Lady-Luck** [Killface1980/RW_FacialStuff#22]
Because Steam went down at an opportune time...

Workshop version: https://i.imgur.com/Jagf51t.png (wrinkles seem to be completely broken)
PawnRenderer: https://i.imgur.com/RoaZXFa.png (wrinkles are working but holy heck this looks awful)

**Comment by Lady-Luck** [comment]
Steam seems to be back up now.

**Comment by Killface1980** [comment]
not a bug, just differences with the rendering. 
with changes visible only at such a small scale, it's totally acceptable compared to the code maintenance with a buggy, self-composed texture scaler. the lesser of two evils.
