### ISSUE TITLE
Cant Close Mod Settings Menu

### ISSUE THREAD

**Issue by Lady-Luck** [Killface1980/RW_FacialStuff#23]
Go to Options, Mod Settings, and then Show Settings next to Facial Stuff. Changing the settings updates the config file appropriately, but it's impossible to leave this screen.

Tested on the latest build of the PawnRenderer branch: https://github.com/Killface1980/RW_FacialStuff/tree/a448701304694f9a8975c02655dcbedba23aa007

**Comment by Killface1980** [comment]
Does this happen in the menu screen or in-game?

**Comment by Lady-Luck** [comment]
I've been going to it from the menu screen. I haven't tested it in game.

**Comment by Killface1980** [comment]
Fixed in current build.
