### ISSUE TITLE
Fallback to original texture if bionic version is not available.

### ISSUE THREAD

**Issue by DenJur** [Killface1980/RW_FacialStuff#25]
Using latest version from steam. 

If there are no texture available for bionic eye it will just display no eyes at all. I think in that case it should fallback to original colonist’s eyes instead. That way it will be able to display new textures for parts that it is able to and not break when there is no texture to display. Or alternately fallback to a “generic” bionic texture.

**Comment by Killface1980** [comment]
Should be fixed in the current Git version. Will do some futher testing till I update the Steam version. Thanks for reporting & your suggestion.

**Comment by Killface1980** [comment]
I've added some new checks, body ports should now remain visible if there's no texture for the added part.
