### ISSUE TITLE
Newest steam beta version is broken.

### ISSUE THREAD

**Issue by DenJur** [Killface1980/RW_FacialStuff#26]
Gives exception with new steam version. Mod list is minimal (HugsLib, ModlistBackup, Facialstuff).
Log: https://gist.github.com/071dbbe9e40033355ec610d972bd7523

**Comment by Killface1980** [comment]
Updated, should be fixed.
Reason for this error was a badly written PrepareCarefully check.
Thank you for reporting, I'll leave this open as a bug for now.
