### ISSUE TITLE
Facial stuff no faces bug (Dumbledood on steam)

### ISSUE THREAD

**Issue by Dumbledood** [Killface1980/RW_FacialStuff#28]
Hey mate,

Here's the log share (It's pretty massive); honestly if you don't want to deal, it's chill. Lol. 

https://gist.github.com/c9fa4ba7edc628a26e6576f3617b2796

Here's a couple pictures of the actual bug:

http://imgur.com/a/2ZVhC
http://imgur.com/a/bIeQO

Here's an imgur album of mod list: 
http://imgur.com/a/n6cKm

Thanks mate!

Let me know if you need anything else, or figure anything out!

**Comment by Killface1980** [comment]
hmmm, I guess it's **Show Hair With Hats or Hide All Hats: 0Harmony(1.0.9.1), ShowHair(1.0.0.0)** which causes the trouble.
Your log shows no errors from FS, so the face should be fully generated. SHWHOHAH detours the renderer like FS, but doesn't recognizes the faces. Try disabling SHWHOHAH, as it won't have any effect with FS.

**Comment by Dumbledood** [comment]
Forgot to thank you for helping me out with this. Was able to help someone else out with the same issue already. :)

**Comment by Killface1980** [comment]
You're welcome, thanks for your log and the mod list 👍
