### ISSUE TITLE
Eyes colors 

### ISSUE THREAD

**Issue by Psyhodozer** [Killface1980/RW_FacialStuff#33]
It would be cool, not only to return the colors to the eyes, but to make visible the white color in new version FS 

https://imgur.com/a/GpclR

**Comment by Killface1980** [comment]
>  I wasn't able to add a custom shader, but basically I'd need the transparent one extended by CutOutComplex + my stuff for 4 sides

=> new shader, possible eye color selector, proper transparancy

https://imgur.com/a/qSFal

**Comment by Killface1980** [comment]
Last update reverted the overlay color from black to white.
I also changed the texture type to CutOutComplex, which adds an additional texture (see vanilla beds). Not included yet: color selector for the secondary tex.

**Comment by Killface1980** [comment]
Overlay color is white by default, adds mask texture support, but no setting for the secondary color. I consider it fixed with WIP.
