### ISSUE TITLE
Beard/Mounth of colonists clipping through some modded hats.

### ISSUE THREAD

**Issue by blyatman01** [Killface1980/RW_FacialStuff#35]
I was testing this mod with some mods like Rimatomics and Fashionrimsta, and I noticed that the beard of some colonists was peaking out of a gas mask. Here's a screenshot: https://imgur.com/a/Qi5w6

Sorry for the bad English.

**Comment by blyatman01** [comment]
Oh rigth, I forgot I had also Clutter Hands, sorry if I didn't said it at first. :/

**Comment by Killface1980** [comment]
Should be fixed in the current build on Git.
