### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object, Game Broken

### ISSUE THREAD

**Issue by bandolando** [Killface1980/RW_FacialStuff#48]
So i had been playing with your mod installed for a while, and i only added one mod mid game, Map Renderer, so i could take proper screenshots. Everything had been running well, no problems, until i loaded my save a bit ago and all my pawns appearance had changed, and the defensive position icon was missing its texture and was instead a purple and orange box with an X in it. I can't click on an object without my game freezing, nor can i even generate a world when i try to start a new colony. My game is pretty broke, and my debug log gets absolutely flooded with red messages.

This is one of the errors it floods me with, and it does the same for 3 or 4 other colonists.
Exception drawing Tiffy: System.NullReferenceException: Object reference not set to an instance of an object
  at FacialStuff.CompFace.PostDraw () [0x00000] in <filename unknown>:0 
  at Verse.ThingWithComps.Comps_PostDraw () [0x00000] in <filename unknown>:0 
  at Verse.ThingWithComps.Draw () [0x00000] in <filename unknown>:0 
  at Verse.DynamicDrawManager.DrawDynamicThings () [0x00000] in <filename unknown>:0 

 All normal human colonists. I have one Twilek who gets no error messages, but appearance changed randomly like everyone else. I just got RimWorld about a week ago and its now completely unplayable. Can you please help me get this resolved? 

[output_log.txt](https://github.com/Killface1980/RW_FacialStuff/files/1926842/output_log.txt)

**Comment by bandolando** [comment]
Just did some research, apparently it is Alien Race Framework that broke it. It was updated several hours ago and according to the steam page, has broken a ton of peoples games.

**Comment by bandolando** [comment]
If anyone is having this same issue, you can fix it by unsubscribing to Alien Race Framework on steam and manually installing the version off of GitHub.
[](https://github.com/erdelf/AlienRaces/releases/tag/b18v3)

**Comment by TenshiAkari12** [comment]
I'm fully offline, so that's not exactly my case unfortunately. That, and I don't have alien framework, though, which is the strange thing.

I _do_ however, have Children & Pregnancy, but that hasn't been updated in a while. Tried it with and without it enabled and still ran across the same issue.

**Comment by Killface1980** [comment]
Luckily fixed in the meantime, I'm closing this issue. Thank you!
