### ISSUE TITLE
Parkas/Dusters invisible when worn.

### ISSUE THREAD

**Issue by Mottis86** [Killface1980/RW_FacialStuff#50]
Like the title says, Parkas and Dusters do not show up on the colonists when I wear them. Interestingly enough, they do show on visitors.

![parkaaa](https://user-images.githubusercontent.com/39233130/39964896-2289eaaa-5697-11e8-9a5b-78b0a51208a8.jpg)

When I load my game, I can briefly see the parka on my guy, very briefly, and then it just disappears.

I already tried rebooting the game, disabling all my other mods and then loading the game. neither of which worked. But here's my mod list anyway:

HugsLib
Facial Stuff
Hand Me That Brick
Allow Tool
Fences and Floors

EDIT Nevermind I'm retarded. There's a setting in the mod settings that makes pawns take off the other layer clothing while indoors.

**Comment by Aviuz** [comment]
what editor you use to add those pretty arrows?

**Comment by Mottis86** [comment]
@Aviuz 

Photoshop CS5. I used simple paintbrush for the arrows and used "Drop shadow" feature on the text and the arrows.

**Comment by Aviuz** [comment]
Thanks
