### ISSUE TITLE
Mace weapon error and fix

### ISSUE THREAD

**Issue by RedBaronFlyer** [Killface1980/RW_FacialStuff#61]
I noticed that maces don't have a holding animation like all the other weapons. I saw that there was nothing in the log folder listing any issues, so I decided to take a look at the WeaponExtensionDefs. It appears that there is no mace file for the mod. I put one together pretty quickly. The only mods used were HubsLib, Jecstools, Camera+, and Facial Stuff

This file should fix it. I've posted the code below as well in case the link doesn't work for whatever reason.
[MaceFix.zip](https://github.com/Killface1980/RW_FacialStuff/files/2633358/MaceFix.zip)

The mace uses the same hand positions as the gladius but that should be fine I hope.

Filename:
WeaponExtensionDef_MeleeWeapon_Mace.xml

<?xml version="1.0" encoding="utf-8"?>
<Defs>
<WeaponExtensionDef>
<weapon>MeleeWeapon_Mace</weapon>
<attackAngleOffset IsNull="True" />
<weaponPositionOffset>
<x>0.01</x>
<y>0</y>
<z>-0.02</z>
</weaponPositionOffset>
<aimedWeaponPositionOffset>
<x>0</x>
<y>0</y>
<z>0</z>
</aimedWeaponPositionOffset>
<firstHandPosition>
<x>-0.28</x>
<y>0.005</y>
<z>0.04</z>
</firstHandPosition>
<secondHandPosition>
<x>0</x>
<y>0</y>
<z>0</z>
</secondHandPosition>
<defName>WeaponExtensionDef_MeleeWeapon_Mace</defName>
<label>WeaponExtensionDef_MeleeWeapon_Mace</label>
</WeaponExtensionDef>
</Defs>

Before:

https://steamuserimages-a.akamaihd.net/ugc/963104528641895582/7EE3CA314CC3111565D011C7693C12AF5F2946DC/

After:

https://steamuserimages-a.akamaihd.net/ugc/963104528641895236/B10199F6CEE5E7F3E9F9A5DF84E26E36267AE952/

Sideways view:

https://steamuserimages-a.akamaihd.net/ugc/963104528641894889/A99B031F69417DD5494A066354F13A2EC5A17BEA/

The reason the pawns look slightly different is that I created a new world just in case that file somehow messed it up.

**Comment by Killface1980** [comment]
Added for the next update, thank you very much!
