### ISSUE TITLE
Type Selector tab causes errors/ doesn't work when starting a new game with Prepared Carefully

### ISSUE THREAD

**Issue by mithosaurion** [Killface1980/RW_FacialStuff#66]
Just as the title says it throws up an error when you switch to the tab.  I'm pretty sure it has something to do with the massive amount of mods I use.  If its something obvious I should have noticed, a compatibility issue that's been mentioned or something, I apologize for wasting your time.  Thank you in advance for taking a look.

Enclosed are the relevant files.  No save file, since this occurs before saving.
[Error Files.zip](https://github.com/Killface1980/RW_FacialStuff/files/2774577/Error.Files.zip)

**Comment by sockrocker86** [comment]
I too experience this exact same issue; even with all mods uninstalled except for Facial Stuff and Prepare Carefully.
Whenever I click on the Type Selector tab I get the following error message: 

Exception filling window for FacialStuff.FaceEditor.Dialog_FaceStyling: System.NullReferenceException: Object reference not set to an instance of an object
  at FacialStuff.FaceEditor.Dialog_FaceStyling.DrawTypeSelector (Rect rect) [0x00000] in <filename unknown>:0 
  at FacialStuff.FaceEditor.Dialog_FaceStyling.DrawUI (Rect rect) [0x00000] in <filename unknown>:0 
  at FacialStuff.FaceEditor.Dialog_FaceStyling.DoWindowContents (Rect inRect) [0x00000] in <filename unknown>:0 
  at Verse.Window+<WindowOnGUI>c__AnonStorey0.<>m__0 (Int32 x) [0x00000] in <filename unknown>:0 
Verse.Log:Error(String, Boolean)
Verse.<WindowOnGUI>c__AnonStorey0:<>m__0(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)

**Comment by Killface1980** [comment]
I've disabled the selector if not on map if not on map for the next version.
