### ISSUE TITLE
Exception for filling window for Facial Stuff - editing appearance of children - Incompatibility with Children School and Learning 

### ISSUE THREAD

**Issue by Cattrina** [Killface1980/RW_FacialStuff#69]
<img>https://i.imgur.com/tBKgGuE.png</img>

Trying to use a dresser to edit a child's appearance results in an error Exception for filling window for Facial Stuff unfortunately I cannot see the rest of the error, as the appearance editor window breaks the screen. The Save button does not exist so I cannot close it. All I can is to ctrl + alt + del and forcefully end RimWorld

**Comment by Killface1980** [comment]
Fixed, as FS doesn't support children currently I've diabled the editor for anyone under 15.
