### ISSUE TITLE
FacialStuff eventually breaks if you press 'Randomize' enough times.

### ISSUE THREAD

**Issue by Lady-Luck** [Killface1980/RW_FacialStuff#7]
![](http://i.imgur.com/W1qWJ9C.png)

Pawns stop having heads.

**Comment by Killface1980** [comment]
I set the limit to 512 heads, never thought that one would reach that number.
Will add 512 more blank head records.

**Comment by Lady-Luck** [comment]
Well, I reached it because I was testing the beard chances.

**Comment by Killface1980** [comment]
heightened the limit to 1024 heads per session
