### ISSUE TITLE
Missing prostethic hands

### ISSUE THREAD

**Issue by ZioPao** [Killface1980/RW_FacialStuff#75]
Prostethic\Bionic arms are still not considered as hands. 
In my branch I just modified the _CheckBodyForAddedParts_ method to check for arms and not only hands (prostethics aren't considered as hands for some reasons).

**Comment by Killface1980** [comment]
I've added your code, but I guess some body parts are still kind of buggy since 1.0. I guess I should overhul the body part section. Thank you for providing your updated version to the Steam Community, much appreciated.
